version: "3.1"

services:
  jupyter:
    container_name: picture-locate
    build: .
#    image: tensorflow/tensorflow:2.12.0-gpu-jupyter
    ports:
      - "8888:8888"
    volumes:
      - "./:/tf/notebooks"
      - "/media/leon/SSD_8TB1/CVUSA/:/tf/CVUSA/"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]