version: "3.1"

services:
  jupyter:
    container_name: image-locate
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./:/tf/notebooks"
      - "/media/leon/SSD_8TB/CVUSA/:/tf/CVUSA/"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
